### ISSUE TITLE
.ARM.exidx section name is wrong ?

### ISSUE THREAD

**Issue by metebalci** [STMicroelectronics/cmsis_device_h5#2]
In [Source/Templates/gcc/linker/STM32H563xx_RAM.ld](https://github.com/STMicroelectronics/cmsis_device_h5/blob/v1.1.0/Source/Templates/gcc/linker/STM32H563xx_RAM.ld), the output section is named `.ARM`. I am not sure as I am not using these but I think, this has to be named `.ARM.exidx` according to [Exception Handling ABI for the Arm® Architecture](https://github.com/ARM-software/abi-aa/blob/2a70c42d62e9c3eb5887fa50b71257f20daca6f9/ehabi32/ehabi32.rst#sections)

```
.ARM : {
    . = ALIGN(4);
    __exidx_start = .;
    *(.ARM.exidx*)
    __exidx_end = .;
    . = ALIGN(4);
  } >RAM
```

The other output section is correctly named `.ARM.extab`.

I did not check all but it might be the case for some of the other or all linker scripts.

**Comment by TOUNSTM** [comment]
Hello @metebalci,

you're right about this point, it is recommended to follow naming conventions to ensure optimal readability of the code. it would be cleaner to rename these sections to .ARM.exidx as is the case in the linker script that is used by default. Unfortunately, our development teams have no plan to implement this change-request.

Please allow me to close this thread. Thank you for your comprehension.

With regards,
